
##################################################################################################
# Reviews service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: jk-app
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  namespace: jk-app
  labels:
    account: ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: jk-app
  labels:
    app: ratings
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v1
  template:
    metadata:
      labels:
        app: ratings
        version: v1
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
      - name: ratings
        # image: 424202621926.dkr.ecr.ap-northeast-2.amazonaws.com/jk-ecr-repository/ratings-v1:latest
        image: AWS_ECR_URI
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
---