version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.12/2020-07-08/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - mkdir ~/.kube
      - aws eks --region ap-northeast-2 update-kubeconfig --name jk-cluster
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build Starting on `date`
      - echo Building the Docker image...
      - export DOCKER_TAG=$(date '+%Y-%m-%d-%s')
      - echo $DOCKER_TAG
      - docker build -t $IMAGE_REPO_NAME:$DOCKER_TAG --build-arg service_version=v1 .
      - docker tag $IMAGE_REPO_NAME:$DOCKER_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$DOCKER_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$DOCKER_TAG
  post_build:
    commands:
      - echo apply .yaml file
      - AWS_ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$DOCKER_TAG
      - sed -i.bak 's#AWS_ECR_URI#'"$AWS_ECR_URI"'#' ./k8s/deploy-details.yaml
      - kubectl apply -f ./k8s/deploy-details.yaml
      - kubectl apply -f ./k8s/virtual-details-add.yaml