apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: reviews
  namespace: jk-app
spec:
  awsName: reviews-virtual-node
  podSelector:
    matchLabels:
      app: reviews
  listeners:
    - portMapping:
        port: 9080
        protocol: http
  serviceDiscovery:
    dns:
      hostname: reviews.jk-app.svc.cluster.local
  backends:
    - virtualService:
        virtualServiceRef:
          name: ratings
  logging:
    accessLog:
      file:
        path: "/dev/stdout"
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualService
metadata:
  name: reviews
  namespace: jk-app
spec:
  awsName: reviews
  provider:
    virtualNode:
      virtualNodeRef:
        name: reviews